import type { MetadataRoute } from "next";

// PWA manifest (Next.js built-in). Served at /manifest.webmanifest and linked
// automatically. Icons live in /public and are generated by scripts/generate-icons.mjs.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "SwipeJobs — Ferizaj",
    short_name: "SwipeJobs",
    description:
      "Swipe-based job matching connecting hourly and shift workers with local businesses in Ferizaj.",
    start_url: "/",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: "#4f46e5",
    orientation: "portrait",
    lang: "sq",
    dir: "ltr",
    categories: ["business", "productivity"],
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
      { src: "/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
